driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: gcp

verifier:
  name: terraform
  systems:
  - name: bucket
    backend: local

suites:
  - name: "bucket"
    driver:
      root_module_directory: test/fixtures/bucket