---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
- name: gcp

verifier:
  name: terraform
  systems:
  - name: bucket
    backend: local

suites:
- name: "barebones"
  driver:
    root_module_directory: examples/barebones-test-fixture